### ISSUE TITLE
Conditionally ignore floating environments

### ISSUE THREAD

**Issue by javaprog** [mhelvens/latex-noindentafter#2]
I use the `\NoIndentAfterEnv` macro for the `listing` and `figure` environments. While larger listings and figures should float to the top or bottom of the page, smaller ones should be in-place to not disturb the flow of reading. It would be nice if this package could be extended such that it only removes the indent if no floating placement modifier is given and the listing or figure is in-place instead of floating.

**Comment by mhelvens** [comment]
This makes sense, and I'd be happy to have it as part of the package.

The problem is, I'm currently swamped with other work. Also, I've not programmed for LaTeX in quite some time, so I'm a bit out of it, mentally.

For those reasons, I don't see myself implementing this any time soon. But if you (or anyone) wants to submit a pull request, I will certainly test it, merge it and publish it.

**Comment by mrpiggi** [comment]
This is really hard to distinguish and even if you are using a placement modifier you can not be sure, that it isn't floating anyways. So, if you don't want your content floating, _do not use_ a floating environment! A simple solution would be to create a specific environment using a [`minipage`](https://tex.stackexchange.com/a/8631/38481) or [`adjustbox`](https://tex.stackexchange.com/a/469244/38481). You can even create the specific environment directly:
```latex
\documentclass{minimal}
\usepackage[T1]{fontenc}
\usepackage{mwe}
\usepackage{noindentafter}

\makeatletter
\newcommand*\nonfloating@begin[1]{%
  \def\@captype{#1}%
  \vskip\intextsep%
  \color@vbox%
    \normalcolor%
    \vbox\bgroup%
      \hsize=\columnwidth%
      \@parboxrestore%
      \@floatboxreset%
      \@setnobreak%
      \ignorespaces%
}
\newcommand*\nonfloating@end{%
      \vskip\intextsep%
      \@minipagefalse%
      \outer@nobreak%
    \egroup%
  \color@endbox%
}
\newenvironment{nonfloatingfigure}{\nonfloating@begin{figure}}{\nonfloating@end}
\newenvironment{nonfloatingtable}{\nonfloating@begin{table}}{\nonfloating@end}
\makeatother

\NoIndentAfterEnv{nonfloatingfigure}

\begin{document}

\blindtext

\begin{nonfloatingfigure}
\centering
\includegraphics{example-image}
\end{nonfloatingfigure}

\blindtext

\end{document}
```
Remark: This will only work after https://github.com/mhelvens/latex-noindentafter/pull/4 has been accepted and shipped to CTAN.
